export default {
  'de': {
    'NCZONE': 'nC Zone',

    'NCZONE_LOGGEDIN': 'Eingeloggt',
    'NCZONE_LOGIN': 'Einloggen',
    'NCZONE_LOGOUT': 'Ausloggen',
    'NCZONE_DRAW': 'Losen',
    'NCZONE_NO_LOGIN': 'Keiner eingeloggt :(',

    'NCZONE_LINKS': 'Links',
    'NCZONE_ZONE': 'Teh Zone',
    'NCZONE_INFORMATION': 'Max wichtige Informationen',

    'NCZONE_RMATCHES': 'Laufende Spiele',
    'NCZONE_PMATCHES': 'Vergangene Spiele',
    'NCZONE_TABLE': 'Tabelle',
    'NCZONE_MENU_INFORMATION': 'Informationen',
    'NCZONE_RULES': 'Regeln',
    'NCZONE_SETTINGS': 'Einstellungen',
    'NCZONE_SWITCH_LANG': 'Switch to English',

    'NCZONE_MATCH_MATCH': 'Spiel',
    'NCZONE_MATCH_DRAWER': 'Gelost von',
    'NCZONE_MATCH_MAP': 'Karte',
    'NCZONE_MATCH_CIVS': 'Civs',
    'NCZONE_MATCH_CIVS_BOTH': 'Beide',
    'NCZONE_MATCH_CIVS_TEAM1': 'Team 1',
    'NCZONE_MATCH_CIVS_TEAM2': 'Team 2',
    'NCZONE_MATCH_TIME_SINCE_DRAW': 'Zeit seit dem Losen',
    'NCZONE_MATCH_TEAMS': 'Teams',
    'NCZONE_MATCH_TEAM1': 'Team 1',
    'NCZONE_MATCH_TEAM2': 'Team 2',
    'NCZONE_MATCH_VS': 'VS',
    'NCZONE_MATCH_HAVE_BET': 'Tipps',
  },
  'en': {
    'NCZONE': 'nC Zone',

    'MCP_ZONE_TITLE': 'nC Zone',
    'MCP_PLAYERS_TITLE': 'Player',
    'MCP_CIVS_TITLE': 'Civilizations',
    'MCP_MAPS_TITLE': 'Maps',

    'NCZONE_LOGGEDIN': 'Logged in',
    'NCZONE_LOGIN': 'Login',
    'NCZONE_LOGOUT': 'Logout',
    'NCZONE_DRAW': 'Draw',
    'NCZONE_NO_LOGIN': 'No one logged in :(',

    'NCZONE_LINKS': 'Links',
    'NCZONE_ZONE': 'Teh Zone',
    'NCZONE_INFORMATION': 'Max important Information',

    'NCZONE_RMATCHES': 'Running Matches',
    'NCZONE_PMATCHES': 'Past Matches',
    'NCZONE_TABLE': 'Player Table',
    'NCZONE_MENU_INFORMATION': 'Information',
    'NCZONE_RULES': 'Rules',
    'NCZONE_SETTINGS': 'Settings',
    'NCZONE_SWITCH_LANG': 'Auf Deutsch wechseln',

    'NCZONE_MATCH_MATCH': 'Match',
    'NCZONE_MATCH_DRAWER': 'Drawed by',
    'NCZONE_MATCH_MAP': 'Map',
    'NCZONE_MATCH_CIVS': 'Civilizations',
    'NCZONE_MATCH_CIVS_BOTH': 'Both teams',
    'NCZONE_MATCH_CIVS_TEAM1': 'Team 1',
    'NCZONE_MATCH_CIVS_TEAM2': 'Team 2',
    'NCZONE_MATCH_TIME_SINCE_DRAW': 'Time since draw',
    'NCZONE_MATCH_TEAMS': 'Teams',
    'NCZONE_MATCH_TEAM1': 'Team 1',
    'NCZONE_MATCH_TEAM2': 'Team 2',
    'NCZONE_MATCH_VS': 'VS',
    'NCZONE_MATCH_HAVE_BET': 'Bets',
  }
}
