export default {
  'de': {
    'NCZONE': 'nC Zone',

    'NCZONE_LOGGEDIN': 'Eingeloggt',
    'NCZONE_LOGIN': 'Einloggen',
    'NCZONE_LOGOUT': 'Ausloggen',
    'NCZONE_DRAW': 'Losen',
    'NCZONE_NO_LOGIN': 'Keiner eingeloggt :(',

    'NCZONE_LINKS': 'Links',
    'NCZONE_ZONE': 'Teh Zone',
    'NCZONE_INFORMATION': 'Max wichtige Informationen',

    'NCZONE_RMATCHES': 'Laufende Spiele',
    'NCZONE_PMATCHES': 'Vergangene Spiele',
    'NCZONE_PLAYERS_TABLE': 'Tabelle',
    'NCZONE_MENU_INFORMATION': 'Informationen',
    'NCZONE_RULES': 'Regeln',
    'NCZONE_SETTINGS': 'Einstellungen',
    'NCZONE_SWITCH_LANG': 'Switch to English',

    'NCZONE_MATCH_MATCH': 'Spiel',
    'NCZONE_MATCH_DRAWER': 'Gelost von',
    'NCZONE_MATCH_MAP': 'Karte',
    'NCZONE_MATCH_CIVS': 'Civs',
    'NCZONE_MATCH_CIVS_BOTH': 'Beide',
    'NCZONE_MATCH_CIVS_TEAM1': 'Team 1',
    'NCZONE_MATCH_CIVS_TEAM2': 'Team 2',
    'NCZONE_MATCH_TIME_SINCE_DRAW': 'Zeit seit dem Losen',
    'NCZONE_MATCH_TEAMS': 'Teams',
    'NCZONE_MATCH_TEAM1': 'Team 1',
    'NCZONE_MATCH_TEAM2': 'Team 2',
    'NCZONE_MATCH_VS': 'VS',
    'NCZONE_MATCH_HAVE_BET': 'Tipps',

    'NCZONE_LOADING': 'Lade Daten...',
    'NCZONE_ERROR_LOADING': 'Fehler beim Laden der Daten',
    'NCZONE_NO_PMATCHES': 'Keine vergangenen Spiele',
    'NCZONE_NO_RMATCHES': 'Keine laufenden Spiele',
    'NCZONE_NO_ACTIVE_PLAYERS': 'Keine aktiven Spieler'
  },
  'en': {
    'NCZONE': 'nC Zone',

    'NCZONE_LOGGEDIN': 'Logged in',
    'NCZONE_LOGIN': 'Login',
    'NCZONE_LOGOUT': 'Logout',
    'NCZONE_DRAW': 'Draw',
    'NCZONE_NO_LOGIN': 'No one logged in :(',

    'NCZONE_LINKS': 'Links',
    'NCZONE_ZONE': 'Teh Zone',
    'NCZONE_INFORMATION': 'Max important information',

    'NCZONE_RMATCHES': 'Running matches',
    'NCZONE_PMATCHES': 'Past matches',
    'NCZONE_PLAYERS_TABLE': 'Player list',
    'NCZONE_MENU_INFORMATION': 'Information',
    'NCZONE_RULES': 'Rules',
    'NCZONE_SETTINGS': 'Settings',
    'NCZONE_SWITCH_LANG': 'Auf Deutsch wechseln',

    'NCZONE_MATCH_MATCH': 'Match',
    'NCZONE_MATCH_DRAWER': 'Drawed by',
    'NCZONE_MATCH_MAP': 'Map',
    'NCZONE_MATCH_CIVS': 'Civilizations',
    'NCZONE_MATCH_CIVS_BOTH': 'Both teams',
    'NCZONE_MATCH_CIVS_TEAM1': 'Team 1',
    'NCZONE_MATCH_CIVS_TEAM2': 'Team 2',
    'NCZONE_MATCH_TIME_SINCE_DRAW': 'Time since draw',
    'NCZONE_MATCH_TEAMS': 'Teams',
    'NCZONE_MATCH_TEAM1': 'Team 1',
    'NCZONE_MATCH_TEAM2': 'Team 2',
    'NCZONE_MATCH_VS': 'VS',
    'NCZONE_MATCH_HAVE_BET': 'Bets',

    'NCZONE_LOADING': 'Loading...',
    'NCZONE_ERROR_LOADING': 'Error loading data',
    'NCZONE_NO_PMATCHES': 'No past matches',
    'NCZONE_NO_RMATCHES': 'No running matches',
    'NCZONE_NO_ACTIVE_PLAYERS': 'No active players',

    'NCZONE_TABLE_HEADER_NAME': 'Name',
    'NCZONE_TABLE_HEADER_GAMES': 'G',
    'NCZONE_TABLE_HEADER_WINS': 'W',
    'NCZONE_TABLE_HEADER_LOSSES': 'L',
    'NCZONE_TABLE_HEADER_TIES': 'T',
    'NCZONE_TABLE_HEADER_WINRATE': 'Winrate',
    'NCZONE_TABLE_HEADER_STREAK': 'S',
    'NCZONE_TABLE_HEADER_RATING_CHANGE': 'R+-',
    'NCZONE_TABLE_HEADER_RATING': 'R',
    'NCZONE_TABLE_HEADER_STREAK_RATING': 'SR',
    'NCZONE_TABLE_HEADER_ACTIVITY': 'Activity',
    'NCZONE_TABLE_FOOTER_AVERAGE': 'Average',

    'NCZONE_REASON_NOT_ALLOWED_TO_LOGIN': 'Not allowed to login.',
    'NCZONE_REASON_NOT_AN_ACTIVATED_PLAYER': 'Not an activated player.'
  }
}
